# Generated by Django 5.0.2 on 2024-02-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_capacity", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Auditorium",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                ("mico_count", models.IntegerField(default=0)),
                ("projects_count", models.IntegerField(default=0)),
                ("entrances_count", models.IntegerField(default=0)),
            ],
            bases=("places.place",),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                ("sofa_count", models.IntegerField(default=0)),
                ("seat_count", models.IntegerField(default=0)),
            ],
            bases=("places.place",),
        ),
    ]
