# Generated by Django 5.0.2 on 2024-03-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_capacity",
                    models.IntegerField(default=0, verbose_name="Вместимость"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активное"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auditorium",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                (
                    "mico_count",
                    models.IntegerField(default=0, verbose_name="Количеств микрофонов"),
                ),
                (
                    "projects_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество проекторов"
                    ),
                ),
                (
                    "entrances_count",
                    models.IntegerField(default=0, verbose_name="Количество входов"),
                ),
            ],
            options={
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
            },
            bases=("places.place",),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                (
                    "sofa_count",
                    models.IntegerField(default=0, verbose_name="Количество диванов"),
                ),
                (
                    "seat_count",
                    models.IntegerField(default=0, verbose_name="Сидячих мест"),
                ),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
            },
            bases=("places.place",),
        ),
    ]
