# Generated by Django 5.0.2 on 2024-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditorium",
            name="entrances_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество входов"
            ),
        ),
        migrations.AlterField(
            model_name="auditorium",
            name="mico_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количеств микрофонов"
            ),
        ),
        migrations.AlterField(
            model_name="auditorium",
            name="projects_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество проекторов"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="seat_capacity",
            field=models.PositiveIntegerField(default=0, verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="room",
            name="seat_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Сидячих мест"),
        ),
        migrations.AlterField(
            model_name="room",
            name="sofa_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество диванов"
            ),
        ),
    ]
