# Generated by Django 5.0.2 on 2024-02-27 15:58

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_distribute",
                    models.BooleanField(
                        auto_created=True,
                        blank=True,
                        default=False,
                        editable=False,
                        verbose_name="Подвергалась рассылке",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "event_capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество участников"
                    ),
                ),
                ("datetime_start", models.DateTimeField(verbose_name="Время начала")),
                ("datetime_end", models.DateTimeField(verbose_name="Время конца")),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
            managers=[
                ("event_object", django.db.models.manager.Manager()),
            ],
        ),
    ]
