# Generated by Django 5.0.2 on 2024-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_distribute",
                    models.BooleanField(auto_created=True, blank=True, default=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "event_capacity",
                    models.IntegerField(
                        default=0, verbose_name="Количество участников"
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Время начала")),
                ("end", models.DateTimeField(verbose_name="Время конца")),
            ],
        ),
    ]
