# Generated by Django 5.0.2 on 2024-02-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Organizer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.place",
                verbose_name="Место провидения",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visitors",
            field=models.ManyToManyField(
                related_name="Visitor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Посетители",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("end__isnull", False), ("start__isnull", False)),
                    models.Q(("end__isnull", False), ("start__isnull", True)),
                    models.Q(("end__isnull", True), ("start__isnull", False)),
                    _connector="OR",
                ),
                name="events_event_start_or_end_time",
            ),
        ),
    ]
