# Generated by Django 5.0.2 on 2024-02-19 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(verbose_name="Время конца"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_capacity",
            field=models.IntegerField(default=0, verbose_name="Количество участников"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.IntegerField(
                choices=[(1, "Notactiveevent"), (2, "Activeevent")],
                default=2,
                verbose_name="Статус мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meeting_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planning.meetingroom",
                verbose_name="Зал",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Organizer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planning.room",
                verbose_name="Комната",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="event",
            name="visitors",
            field=models.ManyToManyField(
                related_name="Visitor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Посетители",
            ),
        ),
    ]
