# Generated by Django 5.0.2 on 2024-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_alter_event_end_alter_event_event_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="msg_distribute",
            field=models.BooleanField(auto_created=True, blank=True, default=False),
        ),
    ]
