# Generated by Django 5.0.2 on 2024-02-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Themes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.TextField(max_length=255, verbose_name="Тема выступления"),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
            },
        ),
        migrations.CreateModel(
            name="ConfCall",
            fields=[
                (
                    "eventtype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events_type.eventtype",
                    ),
                ),
                ("call_url", models.URLField(verbose_name="Ссылка на конференцию")),
            ],
            options={
                "verbose_name": "Конференц-звонок",
                "verbose_name_plural": "Конференц-звонки",
            },
            bases=("events_type.eventtype",),
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "eventtype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events_type.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конференция",
                "verbose_name_plural": "Конференции",
            },
            bases=("events_type.eventtype",),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "eventtype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events_type.eventtype",
                    ),
                ),
                (
                    "need_visit",
                    models.BooleanField(
                        default=True, verbose_name="Необходимость посещения"
                    ),
                ),
                (
                    "meeting_theme",
                    models.TextField(max_length=255, verbose_name="Тема собрания"),
                ),
            ],
            options={
                "verbose_name": "Собрание",
                "verbose_name_plural": "Собрания",
            },
            bases=("events_type.eventtype",),
        ),
    ]
