# Generated by Django 5.0.2 on 2024-02-29 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="themes",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Speaker",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Спикер",
            ),
        ),
        migrations.AddField(
            model_name="themes",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events_type.conference"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                through="events_type.Themes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Спикеры",
            ),
        ),
    ]
