# Generated by Django 5.0.2 on 2024-02-27 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="speaker",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Speaker",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Спикер",
            ),
        ),
    ]
